### ISSUE TITLE
у меня голод

### ISSUE THREAD

**Issue by ppxxd** [rqvm/Cristalix#2]
что делать

**Comment by ppxxd** [comment]
кажеца я умру

**Comment by imDaQ** [comment]
Найди дерево в майнкрафте и сломай листья, может быть тебе повезёт...

**Comment by ppxxd** [comment]
эм я на аниике ломал ничего не падало

**Comment by ppxxd** [comment]
ясно разработчик не помогает

**Comment by imDaQ** [comment]
Ем памох чем смох
